---
# tasks file for rm.cowrie
- name: Installing Dependencies For Cowrie
  apt:
    name:
      - git
      - python-virtualenv
      - libssl-dev
      - libffi-dev
      - build-essential
      - libpython3-dev
      - python3-minimal
      - authbind
      - virtualenv
    state: latest
    update_cache: yes
    cache_valid_time: 600

- name: Creating Cowrie User
  user:
    name: "{{ cowrie_user }}"
    home: "{{ cowrie_home }}"

- name: Clone Cowrie Git Repository
  become: yes
  become_user: "{{ cowrie_user }}"
  git: 
    repo: "{{ cowrie_repo }}"
    dest: "{{ cowrie_root }}"
    force: yes

- name: Install Python Dependencies via pip
  become: yes
  become_user: "{{ cowrie_user }}"
  pip: 
    virtualenv: "{{ cowrie_venv }}"
    virtualenv_python: python3
    requirements: "{{ cowrie_root }}/requirements.txt"

- name: Install Cowrie systemd Service
  template:
    src: cowrie.service.j2
    dest: /etc/systemd/system/cowrie.service
  notify:
    - reload systemctl
    - restart cowrie

- name: Enable Cowrie systemd Service at Boot
  systemd:
    name: cowrie
    enabled: yes
    masked: no

- name: Deploy Cowrie Config
  become: yes
  become_user: "{{ cowrie_user }}"
  template:
    src: cowrie.cfg.j2
    dest: "{{ cowrie_root }}/etc/cowrie.cfg"
  notify:
    - restart cowrie

- name: Deploy Cowrie UserDB
  become: yes
  become_user: "{{ cowrie_user }}"
  template:
    src: userdb.txt.j2
    dest: "{{ cowrie_root }}/etc/userdb.txt"
  notify:
    - restart cowrie

- name: Setting Up Fail2Ban-Jail For Cowrie
  include_role:
    name: rm.fail2ban-cowrie